### ISSUE TITLE
Bukkit4fabric Mod Support

### ISSUE THREAD

**Issue by fantahund** [OKTW-Network/FabricProxy#10]
can you add Support for [Bukkit4fabric](https://github.com/BukkitFabric/bukkit4fabric)?

^^

**Comment by fantahund** [comment]
Error Log: https://cpaste.de/erotuwuzap
Crash Report: https://cpaste.de/utihasevip

The server crashes while trying to connect to the server

**Comment by mmis1000** [comment]
The bug is on Bukkit4fabric end.

They used `@Overwrite` to override minecraft buildin method.
Which will essentially break every single mod that want to mixin into the same method.

https://github.com/BukkitFabric/bukkit4fabric/blob/master/src/main/java/com/javazilla/bukkitfabric/mixin/network/MixinHandshakeC2SPacket.java#L28-L38

**Comment by james58899** [comment]
Please report issue to bukkit4fabric.
We can't fix it.

**Comment by fantahund** [comment]
ok thx

**Comment by CCF100** [comment]
btw @fantahund Bukkit4Fabric will likely never fully work completely...
